export const ITINERARY = [
  {
    date: "Thursday, April 2",
    location: "Dublin → Swords",
    hotel: "Portmarnock Resort & Jameson Golf Course",
    transport: "Rental car – Hertz L46042176A0",
    activities: [
      "Land 6pm in Dublin from AMS",
      "Pick up rental car, drive to Swords",
      "Dinner in Malahide (open late)",
    ],
    notes: "If time: Bog of Frogs Loop or Malahide to Portmarnock walk",
    emoji: "✈️",
  },
  {
    date: "Friday, April 3",
    location: "Belfast",
    hotel: "Townhouse Belfast (Airbnb – HMQTT3ZW4B)",
    transport: "Drive",
    activities: [
      "Drive through Fourknocks & Monasterboice",
      "Carlingford & Proleek",
      "Tollymore Forest Park hike",
      "Slieve Foye hike",
      "Belfast Black Taxi Tour (5–6pm)",
      "Dinner in Belfast",
    ],
    notes: "John & Aidan — review hikes along the way",
    emoji: "🏰",
  },
  {
    date: "Saturday, April 4",
    location: "Belfast → Giant's Causeway",
    hotel: "Causeway Hotel #60588",
    transport: "Drive",
    activities: [
      "Black Taxi Tour (90–120 min)",
      "St. George's Market (9am–3pm)",
      "Run along River Lagan",
      "Carrickfergus Castle",
      "Carrick-a-Rede Rope Bridge (closes 5pm)",
      "Portrush — Troggs open to 6pm",
      "Giant's Causeway",
    ],
    notes: "Cathedral Quarter walk",
    emoji: "🌊",
  },
  {
    date: "Sunday, April 5",
    location: "NI → Dublin",
    hotel: "Airbnb – Stoneybatter, Dublin",
    transport: "Return rental car",
    activities: [
      "Morning run along Giant's Causeway",
      "White Rocks — wild swimming & sea caves",
      "Glenariff",
      "EASTER SUNDAY — scenic stops driving south",
    ],
    notes: "3-hour drive. Stoneybatter neighborhood guide linked.",
    emoji: "🐣",
  },
  {
    date: "Monday, April 6",
    location: "Dublin",
    hotel: "Airbnb – Stoneybatter, Dublin",
    transport: "DART",
    activities: [
      "Morning run in Dublin",
      "40 Foot open water swimming",
      "Christchurch Delgany",
      "Wicklow Mountains",
      "Bray Head",
      "Colleen's host family",
      "Glendalough Spink Trail",
    ],
    notes: "Wicklow Way walk option",
    emoji: "🏔️",
  },
  {
    date: "Tuesday, April 7",
    location: "Dublin",
    hotel: "Airbnb – Stoneybatter, Dublin",
    transport: "Walk/DART",
    activities: [
      "Phoenix Park",
      "St. Stephen's Green",
      "Trinity College",
      "Grafton Street",
      "Live music — Brazen Head or Ned O'Shea's (Seisiún)",
    ],
    notes: "Bring swim suit, goggles & running gear",
    emoji: "🎵",
  },
  {
    date: "Wednesday, April 8",
    location: "Dublin → Manchester → Sheffield",
    hotel: "Airbnb – Fargate Haven, Sheffield (Sleeps 7)",
    transport: "RyanAir FR556 DUB→MAN 12:25pm, arrive 1:25pm. Rental car – Expedia 73391538738009",
    activities: [
      "Afflecks in Manchester",
      "Stroll along River Don, Sheffield",
      "Rivelin Valley Park hike",
      "Kelham Island food & shops",
      "Bear Tree Records",
      "The Indie Arcade",
      "The Gardeners Rest Pub",
    ],
    notes: "Return rental car in Birmingham airport",
    emoji: "🛫",
  },
  {
    date: "Thursday, April 9",
    location: "Sheffield / North Wales",
    hotel: "TBD",
    transport: "Drive",
    activities: [
      "Peak District NP — Rivelin Valley Trail",
      "Drive to North Wales",
      "Llangefni Market (5:30am–2:30pm)",
      "Mold Market (on the way)",
      "Beaumaris Castle",
      "Caernarfon Castle",
    ],
    notes: "3-hour drive to Beaumaris",
    emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  },
  {
    date: "Friday, April 10",
    location: "Birmingham",
    hotel: "Hotel du Vin, Birmingham",
    transport: "Train to Birmingham",
    activities: [
      "Watkin Path hike — Snowdonia",
      "Visit Tori in Birmingham",
      "Drop off rental car at Birmingham airport",
    ],
    notes: "3-hour drive to Birmingham. Up early for hiking.",
    emoji: "🚂",
  },
  {
    date: "Saturday, April 11",
    location: "London",
    hotel: "London – Shoreditch area",
    transport: "Victoria or Shoreditch",
    activities: [
      "Edgbaston Village Artisan Market (10am–3pm)",
      "Edgbaston Reservoir parkrun",
      "Train to London (90 min)",
      "Explore London",
    ],
    notes: "Man Utd vs Leeds if budget allows. Henley River 10K/half option.",
    emoji: "🎡",
  },
  {
    date: "Sunday, April 12",
    location: "Fly Home 🏠",
    hotel: "",
    transport: "12:45pm flight from LHR",
    activities: ["Head to Heathrow", "Fly home"],
    notes: "Safe travels!",
    emoji: "✈️",
  },
];
